# Generated by Django 5.2.7 on 2025-11-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
